/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package CustomerUI;

/**
 *
 * @author A
 */
public class SelectService extends javax.swing.JPanel {

    /**
     * Creates new form SelectService
     */
    public SelectService() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pck1label = new javax.swing.JLabel();
        choosePkglb = new javax.swing.JLabel();
        pck2lb = new javax.swing.JLabel();
        pkg3lb = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        saveAndViewSummaryButton = new javax.swing.JButton();
        chooseDatelb = new javax.swing.JLabel();
        choosePkgComboBox = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SELECT SERVICE PACKAGE");

        pck1label.setBackground(new java.awt.Color(255, 255, 255));
        pck1label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pck1label.setForeground(new java.awt.Color(255, 255, 255));
        pck1label.setText("PACKAGE 1: BATH AND FULL HAIRCUT  -- $50");

        choosePkglb.setBackground(new java.awt.Color(255, 255, 255));
        choosePkglb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        choosePkglb.setForeground(new java.awt.Color(255, 255, 255));
        choosePkglb.setText("CHOOSE YOUR SERVICE PACKAGE");

        pck2lb.setBackground(new java.awt.Color(255, 255, 255));
        pck2lb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pck2lb.setForeground(new java.awt.Color(255, 255, 255));
        pck2lb.setText("PACKAGE 2: BATH AND BRUSH              -- $30");

        pkg3lb.setBackground(new java.awt.Color(255, 255, 255));
        pkg3lb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pkg3lb.setForeground(new java.awt.Color(255, 255, 255));
        pkg3lb.setText("PACKAGE 3: BATH ONLY                          -- $25");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PLACEHOLDER FOR JCAL");

        saveAndViewSummaryButton.setText("SAVE AND VIEW SUMMARY");

        chooseDatelb.setBackground(new java.awt.Color(255, 255, 255));
        chooseDatelb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chooseDatelb.setForeground(new java.awt.Color(255, 255, 255));
        chooseDatelb.setText("CHOOSE APPOINTMENT DATE");

        choosePkgComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PACKAGE 1", "PACKAGE 2", "PACKAGE 3" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(choosePkglb, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chooseDatelb, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(choosePkgComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pck1label, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                    .addComponent(pck2lb, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pkg3lb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(saveAndViewSummaryButton)
                .addGap(260, 260, 260))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addComponent(pck1label)
                .addGap(29, 29, 29)
                .addComponent(pck2lb)
                .addGap(18, 18, 18)
                .addComponent(pkg3lb)
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(choosePkglb)
                    .addComponent(choosePkgComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseDatelb)
                    .addComponent(jLabel6))
                .addGap(57, 57, 57)
                .addComponent(saveAndViewSummaryButton)
                .addContainerGap(100, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chooseDatelb;
    private javax.swing.JComboBox<String> choosePkgComboBox;
    private javax.swing.JLabel choosePkglb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel pck1label;
    private javax.swing.JLabel pck2lb;
    private javax.swing.JLabel pkg3lb;
    private javax.swing.JButton saveAndViewSummaryButton;
    // End of variables declaration//GEN-END:variables
}
