/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.storeManagement;

import Models.Appointment;
import Models.StoreEmployee;
import Utilities.AppointmentController;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chait
 */
public class ReviewClientAppointment extends javax.swing.JPanel {

    /**
     * Creates new form reviewClientAppointment
     */
    JPanel bottomPanel;
    Appointment appointment;
    StoreEmployee storeEmployee;

    public ReviewClientAppointment(StoreEmployee storeEmployee, Appointment appointment, JPanel bottomPanel) {
        initComponents();

        this.bottomPanel = bottomPanel;
        this.appointment = appointment;
        this.storeEmployee = storeEmployee;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitAppointment = new javax.swing.JButton();
        viewAppTitleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        smReviewAppointmentTable = new javax.swing.JTable();
        smBackToServiceOptions = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));

        submitAppointment.setText("COMPLETE BOOKING");
        submitAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitAppointmentActionPerformed(evt);
            }
        });

        viewAppTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        viewAppTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        viewAppTitleLabel.setText("PLEASE REVIEW YOUR APPOINTMENT");

        smReviewAppointmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STORE NAME", "PET NAME", "SERVICE", "DATE", "STATUS"
            }
        ));
        jScrollPane1.setViewportView(smReviewAppointmentTable);

        smBackToServiceOptions.setText("BACK TO SERVICE OPTIONS");
        smBackToServiceOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smBackToServiceOptionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(viewAppTitleLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(submitAppointment)))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(smBackToServiceOptions)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(smBackToServiceOptions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewAppTitleLabel)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(submitAppointment)
                .addContainerGap(317, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void smBackToServiceOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smBackToServiceOptionsActionPerformed
        // TODO add your handling code here:

        SelectServicePanel typeOfService = new SelectServicePanel(storeEmployee, appointment, bottomPanel);
        bottomPanel.add(typeOfService);
        CardLayout layout = (CardLayout) bottomPanel.getLayout();
        layout.next(bottomPanel);
    }//GEN-LAST:event_smBackToServiceOptionsActionPerformed

    private void submitAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitAppointmentActionPerformed
        // TODO add your handling code here:                          
        try{
            AppointmentController.addAppointment(appointment);
            JOptionPane.showMessageDialog(null, "BOOKING COMPLETE!");
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_submitAppointmentActionPerformed

    public void populateTable() {
        try {
            DefaultTableModel tableModel = (DefaultTableModel) smReviewAppointmentTable.getModel();
            tableModel.setRowCount(0);
//            Date currentDate = new Date();
//            appointment.setDate(currentDate);
            appointment.setStatus("Not Started");

            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String formattedDate = (appointment.getDate() != null) ? sdf.format(appointment.getDate()) : "No Date Set";

            String[] storeServiceData = {appointment.getStoreName(), appointment.getPetName(), appointment.getServiceName(), formattedDate, appointment.getStatus()};
            tableModel.addRow(storeServiceData);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton smBackToServiceOptions;
    private javax.swing.JTable smReviewAppointmentTable;
    private javax.swing.JButton submitAppointment;
    private javax.swing.JLabel viewAppTitleLabel;
    // End of variables declaration//GEN-END:variables
}
