/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.storeManagement;

import Views.systemAdmin.AdminMenu;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author chait
 */
public class StoreManagementLogin extends javax.swing.JPanel {

    /**
     * Creates new form storeManagementLogin
     */
    
    JPanel bottomPanel;
    public StoreManagementLogin(JPanel bottomPanel) {
        initComponents();
        this.bottomPanel = bottomPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        smUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        smRole = new javax.swing.JComboBox<>();
        smLogin = new javax.swing.JButton();
        smPassword = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("STORE MANAGEMENT");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USER NAME");

        smUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smUsernameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PASSWORD");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ROLE");

        smRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CLIENT INFORMATION MANAGER", "STORE EMPLOYEE", "SYSTEM ADMIN" }));

        smLogin.setText("LOGIN");
        smLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(smLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(210, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(smRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(smUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                            .addComponent(smPassword))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel1)
                .addGap(72, 72, 72)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(smUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(smPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(smRole, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(smLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void smUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smUsernameActionPerformed

    private void smLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smLoginActionPerformed
        // TODO add your handling code here:
        
        
        switch(smRole.getSelectedItem().toString()){
                
                    case "CLIENT INFORMATION MANAGER" -> {

                        ClientInformationManager clientInformationManagerObj = new ClientInformationManager(bottomPanel);
                        bottomPanel.add(clientInformationManagerObj);
                        CardLayout layout = (CardLayout) bottomPanel.getLayout();
                        layout.next(bottomPanel);

                    }

                    case "STORE EMPLOYEE" -> {

                        StoreEmployeePanel storeEmployeePanelObj = new StoreEmployeePanel(bottomPanel);
                        bottomPanel.add(storeEmployeePanelObj);
                        CardLayout layout = (CardLayout) bottomPanel.getLayout();
                        layout.next(bottomPanel);
                    }
                    
                    case "SYSTEM ADMIN" -> {
                        
                        
                        AdminMenu adminMenuObj = new AdminMenu(bottomPanel);
                        bottomPanel.add(adminMenuObj);
                        CardLayout layout = (CardLayout) bottomPanel.getLayout();
                        layout.next(bottomPanel);
                        
                    }
                    
    
                    
                    default -> {
                        
                        throw new IllegalArgumentException("please select correct Role");
                    }
        
//        try{
//            AdminLoginCreds adminLoginCreds = new AdminLoginCreds();
//            adminLoginCreds.addCreds();
//
//            char [] passwordChars = passwordField.getPassword();
//            String password = new String(passwordChars);
//
//
//            if (adminLoginCreds.authenticate(smPassword.getText(), password)){
//               
//                
//                switch(adminTypeDropDown.getSelectedItem().toString()){
//                
//                    case "CLIENT INFORMATION MANAGER" -> {
//
//                        PatientOptionPanel patientOptionPanel = new PatientOptionPanel(bottomPanel);
//                        bottomPanel.add(patientOptionPanel);
//                        CardLayout layout = (CardLayout) bottomPanel.getLayout();
//                        layout.next(bottomPanel);
//
//                    }
//
//                    case "STORE EMPLOYEE" -> {
//
//                        DoctorOptionPanel doctorOptionPanel = new DoctorOptionPanel(bottomPanel);
//                        bottomPanel.add(doctorOptionPanel);
//                        CardLayout layout = (CardLayout) bottomPanel.getLayout();
//                        layout.next(bottomPanel);
//                    }
//                    
//                    case "SYSTEM ADMIN" -> {
//                        
//                        
//                        HospitalOptionPanel hospitalOptionPanel = new HospitalOptionPanel(bottomPanel);
//                        bottomPanel.add(hospitalOptionPanel);
//                        CardLayout layout = (CardLayout) bottomPanel.getLayout();
//                        layout.next(bottomPanel);
//                        
//                    }
//                    
//    
//                    
//                    default -> {
//                        
//                        throw new IllegalArgumentException("please select correct Admin Type");
//                    }
//                 
//         
//            }
//
//            }
//
//            else{
//                throw new IllegalArgumentException("Please provide valid credentials");
// 
//            }
//        }
//        
//        catch(IllegalArgumentException e){
//            
//            JOptionPane.showMessageDialog(this, e.getMessage(),"Admin Access Error",JOptionPane.ERROR_MESSAGE);
//            
//        }
    }//GEN-LAST:event_smLoginActionPerformed
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton smLogin;
    private javax.swing.JPasswordField smPassword;
    private javax.swing.JComboBox<String> smRole;
    private javax.swing.JTextField smUsername;
    // End of variables declaration//GEN-END:variables
}
