/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.storeManagement;

import Models.Appointment;
import Models.StoreEmployee;
import java.awt.CardLayout;
import javax.swing.JPanel;


/**
 *
 * @author nosil
 */
public class StoreEmployeeLandingPage extends javax.swing.JPanel {

    /**
     * Creates new form StoreEmployeeLandingPage
     */
    JPanel bottomPanel;
    StoreEmployee storeEmployee;
    Appointment appointment;
    public StoreEmployeeLandingPage(JPanel bottomPanel, StoreEmployee storeEmployee) {
        initComponents();
        this.bottomPanel = bottomPanel;
        this.storeEmployee = storeEmployee;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        manageCustInfoButton = new javax.swing.JButton();
        beginServiceButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SELECT TO BEGIN CUSTOMER SERVICE");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FFWS STORE EMPLOYEE PORTAL");

        manageCustInfoButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        manageCustInfoButton.setText("MANAGE CUSTOMER INFORMATION");
        manageCustInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCustInfoButtonActionPerformed(evt);
            }
        });

        beginServiceButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        beginServiceButton.setText("BEGIN CUSTOMER SERVICE");
        beginServiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beginServiceButtonActionPerformed(evt);
            }
        });

        jButton1.setText("LOGOUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(169, 169, 169))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(manageCustInfoButton)
                        .addGap(181, 181, 181))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(beginServiceButton)
                        .addGap(227, 227, 227))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(106, 106, 106)
                .addComponent(beginServiceButton)
                .addGap(44, 44, 44)
                .addComponent(manageCustInfoButton)
                .addContainerGap(231, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageCustInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCustInfoButtonActionPerformed
        // TODO add your handling code here:
        
        ManageCustomerPanel manageCustomerPanelObj = new ManageCustomerPanel(bottomPanel,storeEmployee);
        bottomPanel.add(manageCustomerPanelObj);
        CardLayout layout = (CardLayout) bottomPanel.getLayout();
        layout.next(bottomPanel);
    }//GEN-LAST:event_manageCustInfoButtonActionPerformed

    private void beginServiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beginServiceButtonActionPerformed
            
        
        StoreClientAppointments storeClientAppointmentsObj = new StoreClientAppointments(bottomPanel, storeEmployee);
        bottomPanel.add(storeClientAppointmentsObj);
        CardLayout layout = (CardLayout) bottomPanel.getLayout();
        layout.next(bottomPanel);

                            
        
    }//GEN-LAST:event_beginServiceButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        StoreManagementLogin storeEmployeeLoginObj = new StoreManagementLogin(bottomPanel, appointment);
        
        bottomPanel.add(storeEmployeeLoginObj);
        CardLayout layout = (CardLayout) bottomPanel.getLayout();
        layout.next(bottomPanel);
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton beginServiceButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manageCustInfoButton;
    // End of variables declaration//GEN-END:variables
}
