/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.customer;

import Models.Appointment;
import Models.Customer;
import Utilities.CredentialsChecker;
import Utilities.CustomerController;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Utilities.EmailSender;
import javax.mail.MessagingException;

/**
 *
 * @author A
 */
public class BookAppPage extends javax.swing.JPanel {

    /**
     * Creates new form BookAppPage
     */
    JPanel bottomPanel;
    Appointment appointment;
    private ArrayList<Customer> customers;
    private Boolean auth = false;

    public BookAppPage(JPanel bottomPanel, Appointment appointment) {
        initComponents();
        this.bottomPanel = bottomPanel;
        this.appointment = appointment;
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        custFirstNameTextField = new javax.swing.JTextField();
        custLastNameTextField = new javax.swing.JTextField();
        custEmailTextField = new javax.swing.JTextField();
        confirmCustEmailTextField = new javax.swing.JTextField();
        loginEmailTextField = new javax.swing.JTextField();
        custSignUpButton = new javax.swing.JButton();
        custLogInButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        confirmPasswordField = new javax.swing.JPasswordField();
        passwordField = new javax.swing.JPasswordField();
        loginPasswordField = new javax.swing.JPasswordField();

        jLabel5.setText("jLabel5");

        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("JOIN FURRY FRIENDS MEMBERSHIP");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LOG IN AS FF MEMBER");

        custFirstNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                custFirstNameTextFieldKeyPressed(evt);
            }
        });

        custLastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custLastNameTextFieldActionPerformed(evt);
            }
        });
        custLastNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                custLastNameTextFieldKeyPressed(evt);
            }
        });

        custEmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custEmailTextFieldActionPerformed(evt);
            }
        });
        custEmailTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                custEmailTextFieldKeyPressed(evt);
            }
        });

        confirmCustEmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmCustEmailTextFieldActionPerformed(evt);
            }
        });
        confirmCustEmailTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                confirmCustEmailTextFieldKeyPressed(evt);
            }
        });

        loginEmailTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginEmailTextFieldKeyPressed(evt);
            }
        });

        custSignUpButton.setText("SIGN UP");
        custSignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custSignUpButtonActionPerformed(evt);
            }
        });

        custLogInButton.setText("LOG IN");
        custLogInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custLogInButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FIRST NAME");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LAST NAME");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("EMAIL");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CONFIRM EMAIL");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CONFIRM PASSWORD");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PASSWORD");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("EMAIL");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("PASSWORD");

        confirmPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                confirmPasswordFieldKeyPressed(evt);
            }
        });

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordFieldKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(custFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(custLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel6)
                                    .addComponent(custEmailTextField)
                                    .addComponent(jLabel7)
                                    .addComponent(confirmCustEmailTextField)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(confirmPasswordField))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(106, 106, 106)
                                    .addComponent(custSignUpButton)
                                    .addGap(118, 118, 118))
                                .addComponent(passwordField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addGap(206, 206, 206))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(loginEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(184, 184, 184)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(loginPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(custLogInButton)
                        .addGap(311, 311, 311))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(custLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(custEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmCustEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(confirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(custSignUpButton)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loginEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loginPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(custLogInButton)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void custLastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custLastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custLastNameTextFieldActionPerformed

    private void custLogInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custLogInButtonActionPerformed
        // TODO add your handling code here:
        try {

            this.customers = CustomerController.getAllCustomers();
            String email = loginEmailTextField.getText();
            char[] passwordChars = loginPasswordField.getPassword();
            String password = new String(passwordChars);

            System.out.println(password);
            if (email == null || email.isEmpty() || password.isEmpty()) {

                throw new IllegalArgumentException("Please Fill out the form before submitting the details");
            } else {
                for (Customer cust : customers) {

                    if (cust.getEmail().equals(email) && cust.getPassword().equals(password)) {

                        auth = true;
//                        CustomerLandingPage customerLandingPageObj = new CustomerLandingPage(bottomPanel, cust, new Appointment());
                        CustomerLandingPage customerLandingPageObj = new CustomerLandingPage(bottomPanel, cust,appointment);

                        bottomPanel.add(customerLandingPageObj);
                        CardLayout layout = (CardLayout) bottomPanel.getLayout();
                        layout.next(bottomPanel);
                        break;
                    }

                }
                if (!auth) {
                    throw new IllegalArgumentException("Invalid credentials");
                }

            }

            clearFields();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, e.getMessage(), "Login Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_custLogInButtonActionPerformed

    private void confirmCustEmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmCustEmailTextFieldActionPerformed
        // TODO add your handling code here:

        try {

            if (confirmCustEmailTextField.getText().matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$")) {

                confirmCustEmailTextField.setForeground(Color.black);

            } else {
                throw new Exception();
            }

        } catch (Exception e) {

            confirmCustEmailTextField.setForeground(Color.red);

        }


    }//GEN-LAST:event_confirmCustEmailTextFieldActionPerformed
    
    /**
    * This method clears the text fields used for customer data input.
    */
    private void clearFields() {

        custFirstNameTextField.setText("");
        custLastNameTextField.setText("");
        custEmailTextField.setText("");
        confirmCustEmailTextField.setText("");
        passwordField.setText("");
        confirmPasswordField.setText("");

    }
    private void custSignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custSignUpButtonActionPerformed
        // TODO add your handling code here:

        String firstName = custFirstNameTextField.getText();
        String lastName = custLastNameTextField.getText();
        String email = custEmailTextField.getText();
        String confirmEmail = confirmCustEmailTextField.getText();
        char[] passwordChars = passwordField.getPassword();
        String password = new String(passwordChars);

        char[] confirmPasswordChars = confirmPasswordField.getPassword();
        String confirmPassword = new String(confirmPasswordChars);

        Customer customer = new Customer();

        try {
            if (firstName == null || firstName.isEmpty() || lastName == null || lastName.isEmpty() || email == null || email.isEmpty()
                    || confirmEmail == null || confirmEmail.isEmpty() || password == null || password.isEmpty()
                    || confirmPassword == null || confirmPassword.isEmpty()) {

                throw new IllegalArgumentException("Please Fill out the form before submitting the details");
            }
            if (!password.equals(confirmPassword) && !email.equals(confirmEmail)) {
                throw new IllegalArgumentException("Email and Password are not mathcing");
            }
            if (!password.equals(confirmPassword)) {
                throw new IllegalArgumentException("Password is not matching");
            }

            if (!email.equals(confirmEmail)) {
                throw new IllegalArgumentException("Email is not matching");
            }
            
            if (CredentialsChecker.checkCustomer(email)) {
                    JOptionPane.showMessageDialog(this, "This email is already in use! Please use another email or login with your existing email!", "Existing User Error!", JOptionPane.ERROR_MESSAGE);
                    return;
                }

            customer.setFirstName(firstName);
            customer.setLastName(lastName);
            customer.setEmail(email);
            customer.setPassword(password);

            CustomerController.addCustomer(customer);
            JOptionPane.showMessageDialog(this, "Customer Registered Successfully", "Successfull Registration", JOptionPane.INFORMATION_MESSAGE);

            String body = "Welcome to Furry Friends Membership, " + firstName + "!\n\n"
                    + "Your account has been created successfully. Your login details are:\n"
                    + "Email: " + email + "\n"
                    + "Password: " + password + "\n\n"
                    + "Enjoy our services!";
            EmailSender.sendEmail(email, "Welcome to Furry Friends!", body);

            clearFields();

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Incomplete Form Submission Error", JOptionPane.ERROR_MESSAGE);
        } catch (MessagingException e) {
            JOptionPane.showMessageDialog(this, "Email could not be sent. Please check your network connection and email settings.", "Email Sending Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_custSignUpButtonActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void custFirstNameTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_custFirstNameTextFieldKeyPressed
        // TODO add your handling code here:

        try {

            if (custFirstNameTextField.getText().matches("^[a-zA-Z ]+$")) {

                custFirstNameTextField.setForeground(Color.black);

            } else {
                throw new Exception();
            }

        } catch (Exception e) {

            custFirstNameTextField.setForeground(Color.red);

        }
    }//GEN-LAST:event_custFirstNameTextFieldKeyPressed

    private void custLastNameTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_custLastNameTextFieldKeyPressed
        // TODO add your handling code here:

        try {

            if (custLastNameTextField.getText().matches("^[a-zA-Z ]+$")) {

                custLastNameTextField.setForeground(Color.black);

            } else {
                throw new Exception();
            }

        } catch (Exception e) {

            custLastNameTextField.setForeground(Color.red);

        }
    }//GEN-LAST:event_custLastNameTextFieldKeyPressed

    private void custEmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custEmailTextFieldActionPerformed
        // TODO add your handling code here:

        try {

            if (custEmailTextField.getText().matches("^[a-zA-Z]*")) {

                custEmailTextField.setForeground(Color.black);

            } else {
                throw new Exception();
            }

        } catch (Exception e) {

            custEmailTextField.setForeground(Color.red);

        }
    }//GEN-LAST:event_custEmailTextFieldActionPerformed

    private void loginEmailTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginEmailTextFieldKeyPressed
        // TODO add your handling code here:

        try {

            if (loginEmailTextField.getText().matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$")) {

                loginEmailTextField.setForeground(Color.black);

            } else {
                throw new Exception();
            }

        } catch (Exception e) {

            loginEmailTextField.setForeground(Color.red);

        }


    }//GEN-LAST:event_loginEmailTextFieldKeyPressed

    private void custEmailTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_custEmailTextFieldKeyPressed
        // TODO add your handling code here:

        try {

            if (custEmailTextField.getText().matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$")) {

                custEmailTextField.setForeground(Color.black);

            } else {
                throw new Exception();
            }

        } catch (Exception e) {

            custEmailTextField.setForeground(Color.red);

        }
    }//GEN-LAST:event_custEmailTextFieldKeyPressed

    private void confirmCustEmailTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmCustEmailTextFieldKeyPressed
        // TODO add your handling code here:

        try {

            if (confirmCustEmailTextField.getText().matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$")) {

                confirmCustEmailTextField.setForeground(Color.black);

            } else {
                throw new Exception();
            }

        } catch (Exception e) {

            confirmCustEmailTextField.setForeground(Color.red);

        }
    }//GEN-LAST:event_confirmCustEmailTextFieldKeyPressed

    private void passwordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_passwordFieldKeyPressed

    private void confirmPasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmPasswordFieldKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_confirmPasswordFieldKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField confirmCustEmailTextField;
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JTextField custEmailTextField;
    private javax.swing.JTextField custFirstNameTextField;
    private javax.swing.JTextField custLastNameTextField;
    private javax.swing.JButton custLogInButton;
    private javax.swing.JButton custSignUpButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField loginEmailTextField;
    private javax.swing.JPasswordField loginPasswordField;
    private javax.swing.JPasswordField passwordField;
    // End of variables declaration//GEN-END:variables
}
